[package]
name = "constraint_module"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abi_stable = "0.10.3"
aorist_core = {path = "../aorist_core", features=["python"]}
