---
kind: pipeline
type: kubernetes
name: default

steps:
- name: compile-release
  image: docker.io/scienz/aorist-build:20210519
  commands:
  - cargo build --release
  # Tests must be run with extension-module disabled, see Cargo.toml
  - cargo test --release --no-default-features

trigger:
  event:
    include:
    - push
