---
kind: pipeline
type: kubernetes
name: default

steps:
- name: compile-release
  image: docker.io/scienz/aorist-base:20210518d
  commands:
  - cargo build --release

trigger:
  event:
    include:
    - push
