---
kind: pipeline
type: kubernetes
name: default

steps:
- name: compile-release
  image: scienz/aorist-base:20210518c
  commands:
  - cargo build --release

trigger:
  event:
    include:
    - push
