[package]
name = "aorist"
description = "Dataorist."
version = "0.0.1"
edition = "2018"
repository = "https://github.com/scie-nz/aorist"
license = "MIT"
keywords = ["etl"]
build = "build.rs"
authors = [
  "Bogdan State <bogdan@scie.nz>",
]

[features]
map_first_last = []
rustfmt = []
cargo-fmt = []
trace_macros = []

[lib]
name = "lib"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies.thiserror]
version = "^1.0"

[dependencies.rand]
version = "^0.6"

[dependencies.serde_json]
version = "^1.0"

[dependencies.ordered-float]
version = "2.0.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
aorist_concept = {path = "./aorist_concept"}
aorist_derive = {path = "./aorist_derive"}
aorist_primitives = {path = "./aorist_primitives"}
indoc = "1.0.3"
enum_dispatch = {version = "0.3.5"}
hyphenation = "0.8.0"
paste = {git = "https://github.com/scie-nz/paste", branch = "main"}
uuid = {version = "0.8.1", features = ["v4", "serde"]}
derivative = {version = "2.1.1"}
siphasher = {version = "0.3"}
Inflector = {version = "0.11.4"}
linked-hash-map = "0.5.3"
linked_hash_set = "0.1.4"
pyo3 = {git = "https://github.com/PyO3/pyo3", features = ["extension-module"]}
textwrap = {version = "0.13.2", features = ["hyphenation"]}
sqlparser = {version = "0.6.1"}
maplit = {version = "1.0.2"}

[build-dependencies]
aorist_util = {path = "./aorist_util"}
aorist_primitives = {path = "./aorist_primitives"}
codegen = {version = "0.1.3"}
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
indoc = "1.0.3"
Inflector = {version = "0.11.4"}

