[package]
name = "aorist"
description = "Dataorist."
version = "0.0.1"
edition = "2018"
repository = "https://github.com/scie-nz/aorist"
license = "MIT"
keywords = ["etl"]
build = "build.rs"
authors = [
  "Bogdan State <bogdan@scie.nz>",
]

[features]
map_first_last = []
rustfmt = []
cargo-fmt = []
trace_macros = []

[lib]
name = "lib"
path = "src/lib.rs"

[dependencies.thiserror]
version = "^1.0"

[dependencies.clap]
version = "^2.33"

[dependencies.rand]
version = "^0.6"

[dependencies.rustc-serialize]
version = "^0.3"

[dependencies.serde_json]
version = "^1.0"

[dependencies.nalgebra]
version = "0.21.1"

[dependencies.rayon]
version = "1.3.1"

[dependencies.crossbeam]
version = "0.7.3"

[dependencies.ordered-float]
version = "2.0.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
aorist_concept = {path = "./aorist_concept"}
aorist_derive = {path = "./aorist_derive"}
aorist_primitives = {path = "./aorist_primitives"}
gitea = {path = "./gitea"}
ranger = {path = "./ranger"}
getset = {path = "./getset"}
indoc = "1.0.3"
async-trait = "0.1.41"
futures = "0.3"
tokio = { version = "0.2", features = ["macros"] }
reqwest = { version = "0.10", features = ["json"] }
enum_dispatch = {version = "0.3.4"}
textwrap = {version = "0.12.1"}
git2 = {version = "0.13.12"}
sqlparser = {version = "0.6.1"}
rustpython-vm = { git = "https://github.com/RustPython/RustPython" }
rustpython-parser = { git = "https://github.com/RustPython/RustPython" }
paste = {path = "./paste"}
maplit = {version = "1.0.2"}
uuid = {version = "0.8.1", features = ["v4", "serde"]}
derivative = {version = "2.1.1"}
siphasher = {version = "0.3"}
Inflector = {version = "0.11.4"}
linked-hash-map = "0.5.3"

[build-dependencies]
aorist_util = {path = "./aorist_util"}
aorist_primitives = {path = "./aorist_primitives"}
codegen = {version = "0.1.3"}
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
indoc = "1.0.3"
Inflector = {version = "0.11.4"}

[[bin]]
name = "main"
path = "src/main.rs"
