[package]
name = "dataorist"
description = "Dataorist."
version = "0.0.1"
edition = "2018"
repository = "https://github.com/scie-nz/dataorist"
license = "MIT"
keywords = ["etl"]

authors = [
  "Bogdan State <bogdan@scie.nz>",
]

[features]
map_first_last = []
rustfmt = []
cargo-fmt = []

[lib]
name = "lib_rickworld"
path = "src/lib.rs"

[dependencies.thiserror]
version = "^1.0"

[dependencies.clap]
version = "^2.33"

[dependencies.rand]
version = "^0.6"

[dependencies.rustc-serialize]
version = "^0.3"

[dependencies.serde_json]
version = "^1.0"

[dependencies.nalgebra]
version = "0.21.1"

[dependencies.rayon]
version = "1.3.1"

[dependencies.crossbeam]
version = "0.7.3"

[dependencies.ordered-float]
version = "2.0.0"

[dependencies.riker]
version = "0.4.1"

[[bin]]
name = "main"
path = "src/main.rs"
