---
# Source: kamus/templates/serviceaccount-controller.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kamus-controller
---
# Source: kamus/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kamus
---
# Source: kamus/templates/kamussecret-crd.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kamus-controller
type: Opaque
data:
  certificate.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNVENDQWhtZ0F3SUJBZ0lRWjFUVlZ4T3BRU0RqSlZUVndKZG8vVEFOQmdrcWhraUc5dzBCQVFzRkFEQVQKTVJFd0R3WURWUVFERXdocllXMTFjeTFqWVRBZUZ3MHlNREV3TXpBd01USTFORFphRncwek1ERXdNamd3TVRJMQpORFphTUJBeERqQU1CZ05WQkFNVEJXdGhiWFZ6TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCCkNnS0NBUUVBM05BYzZIYzhUczVBLzFiQ2dBTC9wWE1kS3h0Y3MxdWREZDA1ZzdpUlJDYnFZaHB6UG9vL213TGsKVFhlc0hVUWpGTVB1dWNiOFRtRWdNcXdCRzk2ZGZERnVrYllUM3hQcmEwa3V2NlJIMzhUNG5XT0ZpTy8xd05tTwp3T29tMWpFbTN0UlVQRkJBdGtmMEQ3QXhWNVlCTGpRVUZSRU9OUDB3UU9HRXVWUG9iUStBdk5hV20zbVFiZndNClZzbmJ4bGxVV29oUzFUbjZHMmsvYTNVRlgyMjEwQVU4WVlZNDg1bWpKUXB6elJydnBGRXl6NTVQMytIb2V5RmEKcm5yN0ZZcnQyTTJPWWp4OTRSdWZ6T1VvLzVkK1NRNzQyaHk2OEw2Y3M4M0pDMms2aVB3bE9yYlVDVjFtWmtNaAp1dlpLSG5iTzhZcXZrcCtHRlRqeHFuQTVwemNKT1FJREFRQUJvNEdETUlHQU1BNEdBMVVkRHdFQi93UUVBd0lGCm9EQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQkIKQmdOVkhSRUVPakE0Z2hocllXMTFjeTFqYjI1MGNtOXNiR1Z5TG1SbFptRjFiSFNDSEd0aGJYVnpMV052Ym5SeQpiMnhzWlhJdVpHVm1ZWFZzZEM1emRtTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQTlWelVqR2h2d1BoVlV1CmNoWFVlS1FkUjFyNlZsTHVPT3FTeC84bUtJUFRnOS84ODE5THA5MkdqSVI0NU1jQ2xBTnlVVnlobHN4QTFFdVAKc1ozV0JLTWNSUU1tbU1JSTFLWUhjTzd2QUpJRURWL2VsYlJNK0xlYjlCM203UVhNbmZuLzNCTVdtR2RjQUllYQo0VHBRRDlrOFpDLzlHSU41UTU1TFZMTVpRTDVZSDdvM08yL2Q4VmRUOXU5eDBBK0QvdFVFS3NuSE53VmFETnNyCmROSnpZNzNTQkFZbGhjUEY0UzZ3bkFTc1JtS1Z4MGdDOUEyZFpwSDUvYVI1TUxsbmlLMU5uanZvamVQZzZYTkQKVzVXWE04ZnNsRnFqR0t3WnNRMEo5bm00cW55Mm1ESWoxeUsxOWcwY2cxZk5pdnQ3Ukp2VUVOS1IzMEpyU3dDcAphQkQ3U0pBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  privateKey.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBM05BYzZIYzhUczVBLzFiQ2dBTC9wWE1kS3h0Y3MxdWREZDA1ZzdpUlJDYnFZaHB6ClBvby9td0xrVFhlc0hVUWpGTVB1dWNiOFRtRWdNcXdCRzk2ZGZERnVrYllUM3hQcmEwa3V2NlJIMzhUNG5XT0YKaU8vMXdObU93T29tMWpFbTN0UlVQRkJBdGtmMEQ3QXhWNVlCTGpRVUZSRU9OUDB3UU9HRXVWUG9iUStBdk5hVwptM21RYmZ3TVZzbmJ4bGxVV29oUzFUbjZHMmsvYTNVRlgyMjEwQVU4WVlZNDg1bWpKUXB6elJydnBGRXl6NTVQCjMrSG9leUZhcm5yN0ZZcnQyTTJPWWp4OTRSdWZ6T1VvLzVkK1NRNzQyaHk2OEw2Y3M4M0pDMms2aVB3bE9yYlUKQ1YxbVprTWh1dlpLSG5iTzhZcXZrcCtHRlRqeHFuQTVwemNKT1FJREFRQUJBb0lCQUZscTRUbjJCdkwyclBWNQpnYnZxK3ZGWjQwYndocUtQQjlOMGNYVDR5Y0txYTZHY2lteVorVlhoWHVoTC9PUEJFdCsyMURaZzhRMGdZYlNECldOT2JXM1RPWTdNWDQ0WWpmK0xyT01ZY1ZZcTFMZVEyUi80REJpYTVNd2pHQ1VJVmwyTUc0ckdsNGY2dXRwT2YKeXV0bjhFUndqRzFYZ2NSTmZ6dlcxek5oV2k3SEpwTTNpNEd4VG5nL25tREY0NVowTGVLRGUrdlNzV29pVGNaQgoxaUNhL0ozdW1wMWhndjFRRklUV3NhZ1RiODhiempOSnlsWno1WWNNUSt3akEyOTg0VHQ5Y3kzaXdDVjNBSVVVCnMvYzJEaGZaVHR0d1lqQUwxYkM5azQ4Y1cvQnM0SlpSc3NjNXlKaGhhRmM5aEZ2OEdiNVlycXh6cTNlSlJDWlEKODkxUnBRRUNnWUVBNGpSeU5sYWVRVzhNRzR2QWNpWEtQK0pWZTJHM3dxNFIyandOVnZNL1l1a1hhcjREckFWVwpPbk14bjlVSFRlMElBbW52SGpjcW9HbG5odHhDUmJEZ3RzQU1xTVpKaytZWGFzTzh6bzJHMDZRZkx0eURFYnhHClpyMDQ1MytoSXRJQzJwcXdyOUIzRklyR1J4b2k3Z1cwdmdSMCtXZEVUTzBWWEFnbGl1cS80cUVDZ1lFQStlWGEKVUJ2ODA5Wnpqb09ZTmhDbVYrRkgwVjhEcFl5eHRwemlIZG5iWDhwSEZzcldFcjZHRU5HY0hET3Q5a25WbXdQNgpjQk8vYWRkUGhHUUJQMFZac1F5L1FDZVdjZ1MvZk9pZWNQL0pYbVJqNUs4ZDJKOFdya2k4U3QyMUdVeDl5cFJ0Ck1OSW5IV2pWU3ZzT3NBaHVxdmluOTRCc05nS1pRR3h5SFVuWU41a0NnWUVBb1hRZnBRczBENjRzTFNrVnBpTzAKOU40ZWQxOHE0d2lOYzMvellZRmpWN3paV3ZYZTl4UWtGTG9OekhBbnM0WWdkbUNZTEsvaGUvZGZ6bEU5K0RJawpZaXczbk90U3J2N0c3Z3hob2VoQU9LVm5JSEtDRnRHVVNsWjYzRGtya1FmbXc1TXYwMzF1MFRtd0JpWHdrb1YrCkdUWmpLM1I2dXBGcDhuTmFJSW9uaGFFQ2dZQmxhcUFINU9QZGdPblN5NXNwVGVhRVFid292MXUyZ3Z2WWRhRGEKcG9CK1JwUkZMcnBrVHdnUHFWR21yRjZNVm5pbStaMVlnTnNzOUNHa1JBV3hqTTZTcU82dzlaLzcwK3Qyb04wMApWTXAvVVZTdENWaWVnaW50UHoyVFVKamZsSWgwZjNvMDF3VGl6Wm5LWFVzZnE3eG1ESlgyUHhzcmJEQ1AwYk1hCktjN2krUUtCZ0ZqcGtQdTdWQkhuL203Q3FpS0EyK3JuTmtSbEZXWjdmSFIxeWxKUktCSVpPWUd3TWdyalhLTGMKTWE3dU5qSmwzY0dCU3BZMlRvbVk1SVdrQnpGQ0pCanJPang2TFkvMEF5QUpVY2lGamR1ZE96eGJJREREWThBdQpVWmVFRzd2NVRXOU50VkovaU5uN0NBdFVGNklQRThpWVR4VS81RkhrUEV0UGRpOHpNNFVICi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
# Source: kamus/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kamus
type: Opaque
data:
  appsettings.secrets.json: CnsKCiJLZXlNYW5hZ2VtZW50IjogeyAKCQkiQUVTIjogeyAiS2V5IjogInJXbldiYUZ1dGF2ZG9lcVVpVllNTkpHdm1qUWgzMXFhSWVqL3ZBeEo5RzA9IiB9IH19
---
# Source: kamus/templates/configmap-controller.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kamus-controller
data:
  KeyManagement__Provider: AESKey
  KeyManagement__AES__UseKeyDeriviation: "false"
  TLS_CERT_FOLDER: /home/dotnet/app/tls
---
# Source: kamus/templates/configmap-decryptor.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kamus-decryptor
data:
  KeyManagement__Provider: AESKey
  KeyManagement__AES__UseKeyDeriviation: "false"
---
# Source: kamus/templates/configmap-encryptor.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kamus-encryptor
data:
  KeyManagement__Provider: AESKey
  KeyManagement__AES__UseKeyDeriviation: "false"
---
# Source: kamus/templates/kamussecret-crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kamussecrets.soluto.com
spec:
  preserveUnknownFields: false
  group: soluto.com
  versions:
  - name: v1alpha1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        properties:
          data:
            type: object
            additionalProperties: true
          serviceAccount: 
            type: string
          type:
            type: string
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          data:
            type: object
            additionalProperties: true
          stringData:
            type: object
            additionalProperties: true
          serviceAccount: 
            type: string
          type:
            type: string
  scope: Namespaced
  names:
    plural: kamussecrets
    singular: kamussecret
    kind: KamusSecret
    shortNames:
     - ks
  conversion:
    strategy: Webhook
    webhookClientConfig:
      service:
        namespace: default
        name: kamus-controller
        path: /api/v1/conversion-webhook
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQWR1Z0F3SUJBZ0lSQUloeVV4eDcwQzV6aWxMalZDK29aRkF3RFFZSktvWklodmNOQVFFTEJRQXcKRXpFUk1BOEdBMVVFQXhNSWEyRnRkWE10WTJFd0hoY05NakF4TURNd01ERXlOVFEyV2hjTk16QXhNREk0TURFeQpOVFEyV2pBVE1SRXdEd1lEVlFRREV3aHJZVzExY3kxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFMa21JV0ZIMkR5RWtidkxYRmdudGRDNU9CSm1ZVWdvM2JrNmlvV2FOR1dpQnoyTnIyQWIKeVZBQjZLTVY2TlkvOG95UjQ4Y3J6K1VQUE5aYXdjczdKcW83S1dpQ0VaUFZKTU9XL29GUWxEUTRpcUtPUFVycAo2Mlo4czZHRGxkdHpaZFdMaGhKSXpPRjhnRDBYNFBFTVQ1MCtKSllwNloySmc5TDE5d2w5bkg4Q0pJYktNTmhtCnJ1ZDJNUzRjNU5wQ0Eya1hmclF6dEpPS2JCVlByMGg4MUV4blVjbUFrbGw2RGFBUitSRjkzZmpIMXZ0RzJiTkkKZncwVU9ZWEZ0alFXVVZNc29vQ1ZyTWNzMTh1MThMTStWWHNtaVFRQkJ0ejJtNUhwSnFoMFFYMEVNUDdXUjZtUQpNOHlLL1lJTmNIM09CMVprUjNqa3VQQitVN2RzNDdGMWZIRUNBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFECkFnS2tNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBUEJnTlZIUk1CQWY4RUJUQUQKQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVFNZEtPTmVld213Tk83UnhTbGMvN05oZE96NysrQi9nUgpJNk4vZENXejRiS3FKV21wRmJjS1UzK1IyWm4rQm54YWpUNXF1MG91R2U0dG9ZTXNCV1U2Q1pLaWVUOEY3eHNLCjhVN2E3WVJXQW5qRlhvN3UyaGZBMlY4RDRpNW9sSHh3VXczOU10a3NJWWRZd3BXbitud0RSNXMwYmxkbTV5cHIKU0ltS0hrdjRYSW5YVkNraVphTUdSN2NXNXNIYmp6UzczSWFjWkptSzNkZWdXOVFuenRkMWhJMlE3OXcyU1Q1bwoyVTVQc040bjBNUnRoL3dlMHRLQWphVmdVL2d1eCtUWUFQZEFwR0U0MHlGZHpBdk9NL1gzSnY0K210aUpBNkZWCmRFQ2hEN0hkblpQMkU5R3FSY0JHVW5OTEtXdTI0Y0FQSnNVTFBCWGJKZmloTVYwaDUwa2oKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
---
# Source: kamus/templates/clusterrole-controller.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kamus-controller
rules:
- apiGroups: ["soluto.com"] # "" indicates the core API group
  resources: ["kamussecrets"]
  verbs: ["watch"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["create", "delete", "patch"]
---
# Source: kamus/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kamus
rules:
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
---
# Source: kamus/templates/clusterrolebinding-controller.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kamus-controller
subjects:
- kind: ServiceAccount
  name: kamus-controller
  namespace: default
roleRef:
  kind: ClusterRole
  name: kamus-controller
  apiGroup: rbac.authorization.k8s.io
---
# Source: kamus/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kamus
subjects:
- kind: ServiceAccount
  name: kamus
  namespace: default
roleRef:
  kind: ClusterRole
  name: kamus
  apiGroup: rbac.authorization.k8s.io
---
# Source: kamus/templates/service-controller.yaml
apiVersion: v1
kind: Service
metadata:
  name: kamus-controller
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: kamus
    component: controller
    chart: kamus-0.4.16
    release: kamus
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8888
      protocol: TCP
      name: kamus-controller

  selector:
    app: kamus
    component: controller
    release: kamus
---
# Source: kamus/templates/service-decryptor.yaml
apiVersion: v1
kind: Service
metadata:
  name: kamus-decryptor
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: kamus
    component: decryptor
    chart: kamus-0.4.16
    release: kamus
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9999
      protocol: TCP
      name: kamus-decryptor
  selector:
    app: kamus
    component: decryptor
    release: kamus
---
# Source: kamus/templates/service-encryptor.yaml
apiVersion: v1
kind: Service
metadata:
  name: kamus-encryptor
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: kamus
    component: encryptor
    chart: kamus-0.4.16
    release: kamus
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80 
      targetPort: 9999
      protocol: TCP
      name: kamus-encryptor
  selector:
    app: kamus
    component: encryptor
    release: kamus
---
# Source: kamus/templates/deployment-controller.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kamus-controller
  labels:
    app: kamus
    component: controller
    chart: kamus-0.4.16
    release: kamus
    heritage: Helm
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  selector:
      matchLabels:
        app: kamus
        release: kamus
        component: controller
  template:
    metadata:
      annotations:
        checksum/config: 13e15ed0a44fa974116a3bf981e7688004447a60ce03ba6c87b34b5925108ddf
        checksum/secret: ee4c8b9698d6c782497c64eaa785505899f2451f097b3d55783030d5f6825524
        checksum/tls-secret: 0525619e2fd4405a3519fa2c8962293d13fe30712f3cbda5f49b127e19c2f235
      labels:
        app: kamus
        release: kamus
        component: controller
    spec:
      serviceAccountName: kamus-controller
      automountServiceAccountToken: true
      containers:
        - name: controller
          image: soluto/kamus:controller-0.8.0.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: secret-volume
              mountPath: /home/dotnet/app/secrets
            - name: tls-secret-volume
              mountPath: /home/dotnet/app/tls
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9999
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9999
          resources:
            limits:
              cpu: 500m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 128Mi
          envFrom:
           - configMapRef:
              name: kamus-controller
      volumes:
        - name: secret-volume
          secret:
            secretName: kamus
        - name: tls-secret-volume
          secret:
            secretName: kamus-controller
---
# Source: kamus/templates/deployment-decryptor.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kamus-decryptor
  labels:
    app: kamus
    component: decryptor
    chart: kamus-0.4.16
    release: kamus
    heritage: Helm
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  selector:
      matchLabels:
        app: kamus
        release: kamus
        component: decryptor
  template:
    metadata:
      annotations:
        checksum/config: e00ae16334b15414fe1a9aeb1f978419d2e1e7ec4df0c7e0645ccf7f52730e65
        checksum/secret: ee4c8b9698d6c782497c64eaa785505899f2451f097b3d55783030d5f6825524
      labels:
        app: kamus
        release: kamus
        component: decryptor
    spec:
      serviceAccountName: kamus
      automountServiceAccountToken: true
      containers:
        - name: decryptor-api
          image: soluto/kamus:decryptor-0.8.0.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: secret-volume
              mountPath: /home/dotnet/app/secrets
          ports:
            - containerPort: 9999
          livenessProbe:
            httpGet:
              path: /api/v1/isAlive
              port: 9999
          readinessProbe:
            httpGet:
              path: /api/v1/isAlive
              port: 9999
          resources:
            limits:
              cpu: 500m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 128Mi
          envFrom:
           - configMapRef:
              name: kamus-decryptor
      volumes:
        - name: secret-volume
          secret:
            secretName: kamus
---
# Source: kamus/templates/deployment-encryptor.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kamus-encryptor
  labels:
    app: kamus
    component: encryptor
    chart: kamus-0.4.16
    release: kamus
    heritage: Helm
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: kamus
      component: encryptor
      release: kamus
  template:
    metadata:
      annotations:
        checksum/config: cd5914f256e6ebaf19e73716f990051113e9a8ffd5bc22f60c14189b891aa7da
        checksum/secret: ee4c8b9698d6c782497c64eaa785505899f2451f097b3d55783030d5f6825524
      labels:
        app: kamus
        component: encryptor
        release: kamus
    spec:
      serviceAccountName: kamus
      automountServiceAccountToken: false
      containers:
        - name: encryptor-api
          image: soluto/kamus:encryptor-0.8.0.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: secret-volume
              mountPath: /home/dotnet/app/secrets
          ports:
            - containerPort: 9999
          livenessProbe:
            httpGet:
              path: /api/v1/isAlive
              port: 9999
          readinessProbe:
            httpGet:
              path: /api/v1/isAlive
              port: 9999
          resources:
            limits:
              cpu: 500m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 128Mi
          envFrom:
           - configMapRef:
              name: kamus-encryptor


        
      volumes:
        - name: secret-volume
          secret:
            secretName: kamus
---
# Source: kamus/templates/autoscaling-decryptor.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kamus-decryptor
  labels:
    app: kamus
    component: decryptor
    chart: kamus-0.4.16
    release: kamus
    heritage: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: kamus-decryptor
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
# Source: kamus/templates/autoscaling-encryptor.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kamus-encryptor
  labels:
    app: kamus
    component: encryptor
    chart: kamus-0.4.16
    release: kamus
    heritage: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: kamus-encryptor
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
