<<<<<<< HEAD
#Used for wheel distribution
#[build-system]
#requires = ["setuptools", "wheel", "setuptools-rust"]

#Used for source distribution
[build-system]
requires = ["maturin>=0.10,<0.11"]
build-backend = "maturin"
=======
#[build-system]
#requires = ["setuptools", "wheel", "setuptools-rust"]
[build-system]
requires = ["maturin>=0.10,<0.11"]
build-backend = "maturin"

>>>>>>> 7824140226b3a96696bdb3e908034751f75dd9af
