apiVersion: v0
kind: DataSet
spec:
  accessPolicies:
    approveSelector:
      department: datascience
      project: crowding-detection
  datumTemplates: 
  - &granule name: GranuleDatum
    type: KeyedStruct
    attributes:
    - name: granule_id
      type: KeyStringIdentifier
    - name: product_id
      type: NullableStringIdentifier
    - name: datatake_identifier
      type: NullableStringIdentifier
    - name: mgrs_tile
      type: NullableStringIdentifier
    - name: sensing_time
      type: NullablePOSIXTimestamp
    - name: total_size
      type: NullableInt64
    - name: cloud_cover
      type: NullableString
    - name: geometric_quality_flag
      type: NullableString
    - name: generation_time
      type: NullablePOSIXTimestamp
    - name: north_lat
      type: FloatLatitude
    - name: south_lat
      type: FloatLatitude
    - name: west_lon
      type: FloatLongitude
    - name: east_lon
      type: FloatLongitude
    - name: base_url
      type: URI
  tables:
  - name: sentinel-2-metadata-table
    type: StaticDataTable
    spec:
      storage:
        location:
          type: GCSLocation
          spec:
            uri: https://storage.googleapis.com/gcp-public-data-sentinel-2/index.csv.gz
        layout:
          type: SingleFileLayout
      encoding:
        type: CSVEncoding
        spec:
          compression: GzipCompression
           header: UpperSnakeCaseCSVHeader
      schema:
        type: TabularSchema
        datumTemplate: *granule
        attributes:
        - granule_id
        - product_id
        - datatake_identifier
        - mgrs_tile
        - sensing_time
        - total_size
        - cloud_cover
        - geometric_quality_flag
        - generation_time
        - north_lat
        - south_lat
        - west_lon
        - east_lon
        - base_url
