[package]
name = "aorist_primitives"
version = "0.1.0"
authors = ["Bogdan State <bogdan@scie.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aorist_derive = {path = "../aorist_derive"}
sqlparser = {version = "0.6.1"}
indoc = "1.0.3"
serde = { version = "1.0", features = ["derive"] }
