[package]
name = "aorist_primitives"
version = "0.1.0"
authors = ["Bogdan State <bogdan@scie.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = {git = "https://github.com/scie-nz/paste", branch = "main"}
aorist_derive = {path = "../aorist_derive"}
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
