[package]
name = "aorist"
version = "0.1.0"
authors = ["Bogdan State <bogdan@scie.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "aorist"
path = "src/lib.rs"
crate-type = ["cdylib"]

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
aorist_constraint = {path = "../aorist_constraint", features=["python"]}
aorist_attributes = {path = "../aorist_attributes", features=["python"]}
aorist_primitives = {path = "../aorist_primitives", features=[]}
aorist_core = {path = "../aorist_core", features=["python"]}
aorist_util = {path = "../aorist_util"}
maplit = "1.0.2"
paste = {git = "https://github.com/scie-nz/paste", branch = "main"}
uuid = {version = "0.8.1", features = ["v4", "serde"]}
anyhow = "1.0"
pyo3 = {version = "0.13.2", features=["auto-initialize"]}
