	package:
  name: "aorist"
  version: "0.0.1"

source:
  - path: ../aorist_util
    folder: aorist_util
  - path: ../aorist_derive
    folder: aorist_derive
  - path: ../aorist_primitives
    folder: aorist_primitives
  - path: ../aorist_concept
    folder: aorist_concept
  - path: ../aorist_ast
    folder: aorist_ast
  - path: ../aorist_attributes
    folder: aorist_attributes
  - path: ../aorist_core
    folder: aorist_core
  - path: ../aorist_constraint
    folder: aorist_constraint
  - path: ../aorist
    folder: aorist

build:
  number: 1
  entry_points:
    - aorist=aorist:main
  #script: cd aorist && python setup.py install
  #The script below is fixed for window10-adapt conda-build
  script: cd aorist && set "CARGO_BUILD_TARGET=x86_64-pc-windows-gnu" && python setup.py install

requirements:
  host:
    - python
    - setuptools-rust
    - setuptools
    - conda-build
  run:
    - python
    - astor==0.8.1
    - black
    - dill
    - rpy2

about:
  home: "https://github.com/scie-nz/aorist"
  license: MIT
  license_family: MIT
  license_file:
  summary: "Aorist is a code-generation tool for MLOps. Its aim is to generate legible code for common repetitive tasks in data science, such as data replication, common transformations, as well as machine learning operations."

