# from: https://github.com/helm/charts/issues/5167#issuecomment-641558251
{{- $postgresPass := (randAlpha 32) | b64enc | quote -}}
{{- $postgresSecret := (lookup "v1" "Secret" "aorist" "airflow-postgres") -}}
{{- if $postgresSecret -}}
{{-  $postgresPass = index $postgresSecret.data "pass" -}}
{{- end -}}

# HACK: get values from other namespace
{{- $gitSecret := (lookup "v1" "Secret" "scienz" "git-sync") -}}
{{- $gitIdRsa := index $gitSecret.data "id_rsa" -}}
{{- $ldapSecret := (lookup "v1" "Secret" "scienz" "openldap-account-airflow") -}}
{{- $ldapPass := index $ldapSecret.data "pass" -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: git-sync
  namespace: aorist
  labels:
    app: airflow
type: Opaque
data:
  id_rsa: {{ $gitIdRsa }}
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-postgres
  namespace: aorist
  labels:
    app: airflow
type: Opaque
data:
  user: {{ "airflow" | b64enc | quote }}
  pass: {{ $postgresPass }}
---
apiVersion: v1
kind: Secret
metadata:
  name: openldap-account-airflow
  namespace: aorist
  labels:
    app: airflow
type: Opaque
data:
  user: {{ "uid=airflow,ou=services,dc=scie,dc=nz" | b64enc | quote }}
  pass: {{ $ldapPass }}
