apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: aorist
  labels:
    app: minio
spec:
  # ensure that only users on the VPN can access the service: assign internal IP for use by public hostname
  # if this is changed, the public DNS record for airflow.datascie.nz must be updated to match
  # TODO figure out how to get letsencrypt certificates, likely via DNS validation? may want a separate private-only ingress manager?
  externalIPs:
  - 172.31.8.10
  ports:
  - name: http # webui on same port
    port: 80
    targetPort: s3
  - name: s3
    port: 9000
    targetPort: s3
  selector:
    app: minio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: aorist
  labels:
    app: minio
spec:
  serviceName: minio
  replicas: 4
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      # Minio complains if we have mixed architectures, so lock it to only run on ARM nodes for now. For example:
      # Error: http://minio-1.minio.aorist.svc.cluster.local:9000/data as has incorrect configuration: Expected platform 'OS: linux | Arch: amd64', found to be running 'OS: linux | Arch: arm64' (*fmt.wrapError)
      nodeSelector:
        kubernetes.io/arch: arm64
      # Run containers as nobody:nogroup
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
      containers:
      - name: minio
        image: minio/minio:RELEASE.2021-01-30T00-20-58Z
        imagePullPolicy: IfNotPresent
        command:
        - /bin/bash
        - -c
        # see https://docs.min.io/docs/distributed-minio-quickstart-guide.html
        - 'minio server http://minio-{0...3}.minio.${NAMESPACE}.svc.cluster.local:9000/data'
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-root
              key: user
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-root
              key: pass
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: s3
          containerPort: 9000
        volumeMounts:
        - name: storage
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: storage # pvc will be named "storage-minio-0"
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 50Gi
