# from: https://github.com/helm/charts/issues/5167#issuecomment-641558251
{{- $postgresPass := (randAlpha 32) | b64enc | quote -}}
{{- $hasuraSecret := (randAlpha 32) | b64enc | quote -}}
{{- $secret := (lookup "v1" "Secret" "aorist" "prefect") -}}
{{- if $secret -}}
{{-  $postgresPass = index $secret.data "postgres-pass" -}}
{{-  $hasuraSecret = index $secret.data "hasura-secret" -}}
{{- end -}}

---

apiVersion: v1
kind: Secret
metadata:
  name: prefect
  namespace: aorist
  labels:
    app: prefect
type: Opaque
data:
  postgres-user: {{ "prefect" | b64enc | quote }}
  postgres-pass: {{ $postgresPass }}
  hasura-secret: {{ $hasuraSecret }}
