package:
  name: "aorist_recipes"
  version: "0.0.1"

source:
  path: .

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - aorist

about:
  home: "https://github.com/scie-nz/aorist"
  license: MIT
  license_family: MIT
  license_file:
  summary: "Recipes for aorist package."

