[package]
name = "aorist_concept"
description = """
Getset, we're ready to go!

A procedural macro for generating the most basic getters and setters on fields.
"""
version = "0.1.1"
authors = ["Bogdan State <bogdan@scie.nz>"]
license = "MIT"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = {version = "1.0.52", features = ["full", "extra-traits", "printing"]}
proc-macro2 = "1.0.24"
type_macro_helpers = { path = "../type_macro_helpers" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
aorist_util = {path = "../aorist_util"}
proc_macro_roids = "0.7.0"

[features]
log_syntax = []
trace_macros = []
